; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "IAssetCare"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "IAssetCare"
#define MyAppExeName "asset-care-backend.exe"

[Setup]
AppId={{533F9F1F-A6CE-4D45-8C17-578B3F5B059C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=c:\Users\kedia\Downloads\Asset\Asset\asset-care-system
OutputBaseFilename=iassetcare-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "c:\Users\kedia\Downloads\Asset\Asset\asset-care-system\release-exe\asset-care-backend.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "c:\Users\kedia\Downloads\Asset\Asset\asset-care-system\release-exe\.env"; DestDir: "{app}"; Flags: ignoreversion
Source: "c:\Users\kedia\Downloads\Asset\Asset\asset-care-system\release-exe\.env.example"; DestDir: "{app}"; Flags: ignoreversion
Source: "c:\Users\kedia\Downloads\Asset\Asset\asset-care-system\release-exe\README.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
